In [1]:
from utility import *

In [ ]:
def delta_OSRG(fig, seed_pos = [0,0]):
    for i in [-1, 0, 1]:
        for j in [-1, 0, 1]:
            total_intensity += fig[seed_pos[0] + i, seed_pos[1] + j]
    intensity_avg = total_intensity / 9 
    return np.abs(fig[seed_pos] - intensity_avg)


def delta_LSRG(fig, seed_x, seed_y):
    slope_x = []
    slope_y = []
    intercept_x = []
    intercept_y = []
    # x linear regression
    for row in [-1, 0, 1]:
        lrx = linregress([seed_x - 1, seed_x, seed_x + 1], fig[seed_y + row, seed_x - 1 : seed_x + 1 ])
        slope_x.append(lrx.slope)
        intercept_x.append(lrx.intercept)
    # y linear regression
    for col in [-1, 0, 1]:
        lry = linregress([seed_y - 1, seed_y, seed_y + 1], fig[seed_y - 1 : seed_y + 1, seed_x + col])
        slope_y.append(lry.slope)
        intercept_y.append(lry.intercept)
    for i in [-1, 0, 1]:
        for j in [-1, 0, 1]:
            


In [2]:
# y = 1.5 * x + 5
x = np.linspace(-1, 1, 3)
y = np.linspace(-1, 1, 3)
x, y = np.meshgrid(x, y)
z = 1.5 * x + 2.5 * y + 5


In [6]:
def func(x, k, b):
    return k * x + b
curve_fit(func, [-1, 0, 1], [1, 2.5, 4])

(array([1.5, 2.5]),
 array([[ 0., -0.],
        [ 0.,  0.]]))

In [4]:
z

array([[1. , 2.5, 4. ],
       [3.5, 5. , 6.5],
       [6. , 7.5, 9. ]])

In [ ]:
y.mean()